// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PetsAPI.Database;
using System;

namespace PetsAPI.Migrations
{
    [DbContext(typeof(PetsDbContext))]
    [Migration("20181005045145_cyclepath")]
    partial class cyclepath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetsAPI.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("Edad");

                    b.Property<string>("Emfermedades");

                    b.Property<string>("Especie");

                    b.Property<bool>("Estado");

                    b.Property<DateTime>("FechaDeRegistro");

                    b.Property<string>("Imagen");

                    b.Property<string>("Nombre");

                    b.Property<string>("Origen");

                    b.Property<string>("Raza");

                    b.Property<string>("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
